apiVersion: v1
kind: ConfigMap
metadata:
  name: open-webui-configmap
  namespace: open-webui
data:
  # Ollama URL for the backend to connect
  # The path '/ollama' will be redirected to the specified backend URL
  ENABLE_OLLAMA_API: false
  OLLAMA_BASE_URL: ''

  ENABLE_OPENAI_API: true
  OPENAI_API_BASE_URL: 'http://192.168.11.201:4000'
  OPENAI_API_KEY: 'dummy'

  RAG_EMBEDDING_ENGINE: "openai"
  # RAG_EMBEDDING_MODEL: ""
  RAG_OPENAI_API_BASE_URL: 'http://192.168.11.201:4000'
  RAG_OPENAI_API_KEY: 'dummy'

  RAG_RERANKING_MODEL: 'BAAI/bge-reranker-v2-m3'

  # DO NOT TRACK
  SCARF_NO_ANALYTICS: true
  DO_NOT_TRACK: true
  ANONYMIZED_TELEMETRY: false

  # Backend settings
  CORS_ALLOW_ORIGIN: "http://localhost:5173;http://localhost:8080;http://192.168.11.53:5173"

  VECTOR_DB: "chroma"
  CHROMA_HTTP_HOST: "192.168.11.204"
  CHROMA_HTTP_PORT: "6666"
